# Generated by Django 5.2.14 on 2026-05-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_address_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(default='AOA', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(default='pt', help_text='pt, en, fr, es', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
