# Generated by Django 6.0.6 on 2026-08-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_social_login'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='accounts_so_provide_71a274_idx',
            old_name='accounts_so_provide_7c8e0a_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_locale',
            field=models.CharField(blank=True, default='pt', help_text='pt, en, fr, es — blank means follow device language', max_length=5),
        ),
    ]
