# Generated by Django 6.0.6 on 2026-08-11 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_currency_locale_fx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Notification preferences: enabled, budget_warnings, budget_exceeded, debt_reminders, savings_reminders, monthly_summary, goal_reminders'),
        ),
        migrations.CreateModel(
            name='AppReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('click', 'Download link click'), ('install', 'App open / install attributed'), ('register', 'User registered')], default='click', max_length=20)),
                ('platform', models.CharField(blank=True, help_text='ios | android | web | unknown', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_referral_events_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_referral_events_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referral_code', 'event_type'], name='accounts_ap_referra_c3f567_idx')],
            },
        ),
    ]
