# Generated by Django 6.0.6 on 2026-08-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_monthly_plan_share_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('apple', 'Apple')], max_length=32),
        ),
    ]
