# Generated by Django 6.0.6 on 2026-08-23 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_device_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('email_host', models.CharField(default='smtpout.secureserver.net', max_length=255)),
                ('email_host_user', models.EmailField(blank=True, default='', max_length=254)),
                ('email_host_password', models.TextField(blank=True)),
                ('default_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_port', models.PositiveIntegerField(blank=True, null=True)),
                ('use_tls', models.BooleanField(blank=True, null=True)),
                ('use_ssl', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_email_server_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração SMTP',
                'verbose_name_plural': 'Configurações SMTP',
            },
        ),
    ]
