# Generated by Django 5.2.14 on 2026-05-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/case-studies/')),
                ('tools_used', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('translations', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('locale', models.CharField(default='pt', max_length=5)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('services_intro', 'Services Intro'), ('portfolio_intro', 'Portfolio Intro'), ('showreel', 'Showreel'), ('zenda', 'Zenda'), ('case_studies_intro', 'Case Studies Intro'), ('testimonials_intro', 'Testimonials Intro'), ('cta', 'Call to Action')], max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('translations', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('campaign_videos', 'Campaign Videos'), ('interviews', 'Interviews'), ('social_reels', 'Social Media Reels'), ('canva_designs', 'Canva Designs'), ('scriptwriting', 'Scriptwriting / Roteiros'), ('zenda_content', 'Zenda Product Content')], max_length=32)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or embed URL')),
                ('external_url', models.URLField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('tools_used', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('translations', models.JSONField(default=dict, help_text='{"pt": {"title": "", "description": "", "role": ""}, "en": {...}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='video', help_text='Icon key: video, script, interview, etc.', max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('translations', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShowreelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('youtube_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='contacto@rubianejoaquim.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='244944905246', max_length=32)),
                ('phone', models.CharField(default='+244 944 905246', max_length=32)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='portfolio/og/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_role', models.CharField(blank=True, max_length=200)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='portfolio/testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('translations', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZendaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_store_url', models.URLField(blank=True)),
                ('play_store_url', models.URLField(blank=True)),
                ('monthly_price_kz', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('translations', models.JSONField(default=dict, help_text='Headlines, benefits list, who it helps, etc. per locale')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zenda Content',
                'verbose_name_plural': 'Zenda Content',
            },
        ),
        migrations.CreateModel(
            name='ZendaScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/zenda/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('zenda_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.zendacontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
