# Generated by Django 5.2.14 on 2026-05-21 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('services', 'Services'), ('portfolio', 'Portfolio'), ('courses', 'Courses'), ('mentorship', 'Mentorship'), ('zenda', 'Zenda'), ('payments', 'Payments'), ('support', 'Support'), ('general', 'General')], default='general', max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('translations', models.JSONField(default=dict, help_text='question, answer per locale')),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('translations', models.JSONField(default=dict, help_text='label per locale')),
            ],
            options={
                'verbose_name_plural': 'Homepage statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('placement', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('both', 'Header & Footer')], default='both', max_length=16)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('translations', models.JSONField(default=dict, help_text='{"pt": {"label": "..."}}')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('locale', models.CharField(default='pt', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.SlugField(help_text='home, zenda, portfolio, contact, etc.', max_length=64, unique=True)),
                ('canonical_path', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='portfolio/og/pages/')),
                ('translations', models.JSONField(default=dict, help_text='title, description, keywords, og_title, og_description per locale')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('article', 'Article'), ('template', 'Template'), ('guide', 'Guide')], default='article', max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/resources/')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/resources/files/')),
                ('video_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('translations', models.JSONField(default=dict, help_text='title, description, seo_title, seo_description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service_interest',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='source_page',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendly_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='translations',
            field=models.JSONField(default=dict, help_text='brand_tagline, footer_description, footer_rights per locale'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost'), ('spam', 'Spam'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_key',
            field=models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('services_intro', 'Services Intro'), ('portfolio_intro', 'Portfolio Intro'), ('showreel', 'Showreel'), ('zenda', 'Zenda'), ('case_studies_intro', 'Case Studies Intro'), ('testimonials_intro', 'Testimonials Intro'), ('education', 'Education'), ('final_cta', 'Final CTA'), ('statistics', 'Statistics'), ('cta', 'Call to Action')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='translations',
            field=models.JSONField(default=dict, help_text='title, description, short_description, full_description, features[], cta_text, cta_link, seo_title, seo_description'),
        ),
        migrations.CreateModel(
            name='ZendaFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/zenda/features/')),
                ('category', models.CharField(choices=[('personal_finance', 'Personal Finance'), ('business_finance', 'Business Finance'), ('ai_copilot', 'AI Financial Copilot'), ('currency', 'Currency Converter'), ('education', 'Education'), ('goals', 'Goals'), ('tasks', 'Tasks'), ('subscriptions', 'Subscriptions'), ('notifications', 'Notifications'), ('reports', 'Reports'), ('security', 'Security'), ('offline', 'Offline Mode')], default='personal_finance', max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('translations', models.JSONField(default=dict, help_text='title, description')),
                ('zenda_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='portfolio.zendacontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
