# Generated by Django 6.0.1 on 2026-01-29 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Período de teste'), ('active', 'Ativo'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Fim da semana grátis (7 dias após subscrever)', null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, help_text='Fim do período pago atual (renovado quando admin aprova pagamento)', null=True)),
                ('expiry_reminder_sent_at', models.DateTimeField(blank=True, help_text='Quando foi enviado o aviso de 3 dias antes do fim', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscrição App Móvel',
                'verbose_name_plural': 'Subscrições App Móvel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileAppSubscriptionPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mobile_subscription_proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mobile_subscription_proofs', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='subscriptions.mobileappsubscription')),
            ],
            options={
                'verbose_name': 'Comprovativo Subscrição App',
                'verbose_name_plural': 'Comprovativos Subscrição App',
                'ordering': ['-created_at'],
            },
        ),
    ]
