# Generated by Django 5.2.14 on 2026-05-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_mobile_app_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappsubscription',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('business', 'Business'), ('family', 'Family')], default='premium', help_text='Feature tier: free, premium, business, family', max_length=20),
        ),
    ]
