# Generated by Django 5.2 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_mobileappsubscription_plan_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappsubscription',
            name='status',
            field=models.CharField(
                choices=[
                    ('trial', 'Período de teste'),
                    ('active', 'Ativo'),
                    ('paused', 'Pausado'),
                    ('expired', 'Expirado'),
                    ('cancelled', 'Cancelado'),
                ],
                default='trial',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='mobileappsubscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileappsubscription',
            name='reminder_7d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileappsubscription',
            name='reminder_3d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileappsubscription',
            name='reminder_1d_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mobileappsubscription',
            index=models.Index(fields=['status', 'created_at'], name='subscriptio_status_0dd7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappsubscription',
            index=models.Index(fields=['plan_tier'], name='subscriptio_plan_ti_00677e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappsubscription',
            index=models.Index(fields=['subscription_ends_at'], name='subscriptio_subscri_720abd_idx'),
        ),
        migrations.AlterField(
            model_name='mobileappsubscriptionpaymentproof',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pendente'),
                    ('approved', 'Aprovado'),
                    ('rejected', 'Rejeitado'),
                    ('info_requested', 'Informação pedida'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='mobileappsubscriptionpaymentproof',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mobileappsubscriptionpaymentproof',
            name='currency',
            field=models.CharField(blank=True, default='AOA', max_length=8),
        ),
        migrations.AddField(
            model_name='mobileappsubscriptionpaymentproof',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('bank_transfer', 'Transferência bancária'),
                    ('apple_iap', 'Apple In-App Purchase'),
                    ('card', 'Cartão'),
                    ('other', 'Outro'),
                ],
                default='bank_transfer',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='mobileappsubscriptionpaymentproof',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mobileappsubscriptionpaymentproof',
            name='info_request_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='mobileappsubscriptionpaymentproof',
            index=models.Index(fields=['status', 'created_at'], name='subscriptio_status_03d75c_idx'),
        ),
        migrations.CreateModel(
            name='SubscriptionAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('customer_email', models.CharField(blank=True, max_length=254)),
                ('result', models.CharField(default='success', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='subscription_admin_audit_logs',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('payment_proof', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='audit_logs',
                    to='subscriptions.mobileappsubscriptionpaymentproof',
                )),
                ('subscription', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='audit_logs',
                    to='subscriptions.mobileappsubscription',
                )),
            ],
            options={
                'verbose_name': 'Auditoria Admin Subscrição',
                'verbose_name_plural': 'Auditorias Admin Subscrição',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionadminauditlog',
            index=models.Index(fields=['action', 'created_at'], name='subscriptio_action_919b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionadminauditlog',
            index=models.Index(fields=['customer_email'], name='subscriptio_custome_050498_idx'),
        ),
    ]
