# Generated by Django 6.1 on 2026-08-21 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_ops_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ikhokha', 'iKhokha')], default='ikhokha', max_length=32, unique=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('app_id', models.CharField(blank=True, max_length=128)),
                ('app_secret', models.TextField(blank=True)),
                ('webhook_secret', models.TextField(blank=True)),
                ('api_base_url', models.URLField(blank=True, default='https://api.ikhokha.com/public-api/v1', max_length=300)),
                ('payment_url', models.URLField(blank=True, default='https://api.ikhokha.com/public-api/v1/api/payment', max_length=300)),
                ('callback_url', models.URLField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_gateway_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de gateway',
                'verbose_name_plural': 'Configurações de gateway',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price_aoa', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('monthly_price_zar', models.DecimalField(decimal_places=2, default=180, max_digits=12)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('payee_name', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subscription_billing_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Definições de faturação',
                'verbose_name_plural': 'Definições de faturação',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tier', models.CharField(default='premium', max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=8)),
                ('plan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_currency', models.CharField(max_length=8)),
                ('method', models.CharField(choices=[('proof_of_payment', 'Proof of Payment'), ('card', 'Card'), ('apple_iap', 'Apple In-App Purchase')], max_length=32)),
                ('gateway', models.CharField(choices=[('none', 'None'), ('ikhokha', 'iKhokha'), ('apple', 'Apple')], default='none', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('pending_verification', 'Pending verification'), ('info_requested', 'Info requested'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('refund_requested', 'Refund requested'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('paylink_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('paylink_url', models.URLField(blank=True, max_length=500)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128)),
                ('failure_reason', models.CharField(blank=True, max_length=240)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_payments', to='subscriptions.mobileappsubscriptionpaymentproof')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.mobileappsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de subscrição',
                'verbose_name_plural': 'Pagamentos de subscrição',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='subscriptio_status_9569df_idx'), models.Index(fields=['method', 'status'], name='subscriptio_method_e500c9_idx'), models.Index(fields=['user', 'created_at'], name='subscriptio_user_id_a1e4d8_idx')],
            },
        ),
    ]
