# Generated by Django 6.0.6 on 2026-08-23 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_backfill_subscription_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=16),
        ),
        migrations.CreateModel(
            name='CommercePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('course', 'Course'), ('mentorship', 'Mentorship')], max_length=20)),
                ('product_id', models.PositiveIntegerField()),
                ('enrollment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mentorship_request_id', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZAR', max_length=8)),
                ('plan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_currency', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='processing', max_length=32)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('paylink_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('paylink_url', models.URLField(blank=True, max_length=500)),
                ('provider_status', models.CharField(blank=True, max_length=64)),
                ('failure_reason', models.CharField(blank=True, max_length=240)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento commerce (iKhokha)',
                'verbose_name_plural': 'Pagamentos commerce (iKhokha)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_type', 'product_id'], name='subscriptio_product_9a8229_idx'), models.Index(fields=['status', 'created_at'], name='subscriptio_status_d041be_idx'), models.Index(fields=['user', 'created_at'], name='subscriptio_user_id_c89953_idx')],
            },
        ),
    ]
