# Generated by Django 5.2.1 on 2026-01-27 16:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=100)),
                ('icon', models.CharField(default='check-circle', help_text='Ícone da categoria', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Cor em hexadecimal', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Tarefa',
                'verbose_name_plural': 'Categorias de Tarefas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da notificação', max_length=200)),
                ('message', models.TextField(help_text='Mensagem da notificação')),
                ('notification_type', models.CharField(choices=[('task_reminder', 'Lembrete de Tarefa'), ('target_milestone', 'Marco de Meta'), ('goal_achievement', 'Conquista de Objetivo'), ('payment_due', 'Pagamento Vencendo'), ('system', 'Sistema'), ('achievement', 'Conquista'), ('reminder', 'Lembrete')], default='system', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Notificação lida')),
                ('action_url', models.CharField(blank=True, help_text='URL de ação (opcional)', max_length=500)),
                ('related_object_type', models.CharField(blank=True, help_text='Tipo do objeto relacionado', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID do objeto relacionado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da meta', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada')),
                ('target_type', models.CharField(choices=[('financial', 'Financeira'), ('career', 'Carreira'), ('health', 'Saúde'), ('education', 'Educação'), ('personal', 'Pessoal'), ('business', 'Negócio'), ('other', 'Outro')], default='personal', max_length=50)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor alvo (se aplicável)', max_digits=10, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(blank=True, help_text='Unidade de medida (ex: KZ, kg, horas)', max_length=50)),
                ('start_date', models.DateField(help_text='Data de início')),
                ('target_date', models.DateField(help_text='Data alvo para alcançar')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('milestones', models.JSONField(blank=True, default=list, help_text='Marcos intermediários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da tarefa', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada')),
                ('due_date', models.DateField(blank=True, help_text='Data de vencimento', null=True)),
                ('due_time', models.TimeField(blank=True, help_text='Hora de vencimento', null=True)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Progresso'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('is_recurring', models.BooleanField(default=False, help_text='Tarefa recorrente')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=50, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
