# Generated by Django 6.0.6 on 2026-07-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_reminder', 'Lembrete de Tarefa'), ('target_milestone', 'Marco de Meta'), ('goal_achievement', 'Conquista de Objetivo'), ('goal_reminder', 'Lembrete de Objetivo'), ('payment_due', 'Pagamento Vencendo'), ('system', 'Sistema'), ('achievement', 'Conquista'), ('reminder', 'Lembrete')], default='system', max_length=50),
        ),
    ]
