# Generated by Django 6.0.6 on 2026-08-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_reminder', 'Lembrete de Tarefa'), ('target_milestone', 'Marco de Meta'), ('goal_achievement', 'Conquista de Objetivo'), ('goal_reminder', 'Lembrete de Objetivo'), ('payment_due', 'Pagamento Vencendo'), ('budget_warning', 'Alerta de Orçamento'), ('budget_exceeded', 'Orçamento Excedido'), ('system', 'Sistema'), ('achievement', 'Conquista'), ('reminder', 'Lembrete')], default='system', max_length=50),
        ),
    ]
