# Generated by Django 5.2 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_monthly_plan_share_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('task_reminder', 'Lembrete de Tarefa'),
                    ('target_milestone', 'Marco de Meta'),
                    ('goal_achievement', 'Conquista de Objetivo'),
                    ('goal_reminder', 'Lembrete de Objetivo'),
                    ('payment_due', 'Pagamento Vencendo'),
                    ('budget_warning', 'Alerta de Orçamento'),
                    ('budget_exceeded', 'Orçamento Excedido'),
                    ('subscription_reminder', 'Lembrete de Subscrição'),
                    ('system', 'Sistema'),
                    ('achievement', 'Conquista'),
                    ('reminder', 'Lembrete'),
                ],
                default='system',
                max_length=50,
            ),
        ),
    ]
