# Generated by Django 5.2.7 on 2026-08-21 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_marketplace_foundation'),
        ('mentorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshippackage',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='mentorshippackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorshippackage',
            name='language',
            field=models.CharField(default='pt', max_length=5),
        ),
        migrations.AddField(
            model_name='mentorshippackage',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='instructors.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentorshippackage',
            name='offering_type',
            field=models.CharField(choices=[('one_time', 'One-time session'), ('recurring', 'Recurring'), ('programme', 'Programme')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='mentorshippackage',
            name='programme_outline',
            field=models.JSONField(blank=True, default=list, help_text='[{week, title, description}] for programme offerings'),
        ),
        migrations.AddField(
            model_name='mentorshippackage',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorshippackage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=20),
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='instructors.mentorprofile')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('mentor', 'weekday', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('meeting_provider', models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('daily', 'Daily.co'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('meeting_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='instructors.mentorprofile')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_records', to='mentorship.mentorshippackage')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mentorship.mentorshiprequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [models.UniqueConstraint(fields=('mentor', 'starts_at'), name='uniq_mentor_session_slot')],
            },
        ),
    ]
