# Generated by Django 5.2.1 on 2026-01-27 16:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=100)),
                ('icon', models.CharField(default='tag', help_text='Ícone da categoria', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Cor em hexadecimal', max_length=7)),
                ('is_personal', models.BooleanField(default=True, help_text='Usado para finanças pessoais')),
                ('is_business', models.BooleanField(default=False, help_text='Usado para finanças de negócios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='Descrição da despesa')),
                ('date', models.DateField(help_text='Data da despesa')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('check', 'Cheque'), ('other', 'Outro')], default='cash', max_length=50)),
                ('supplier', models.CharField(blank=True, help_text='Nome do fornecedor', max_length=200)),
                ('invoice_number', models.CharField(blank=True, help_text='Número da fatura', max_length=100)),
                ('is_tax_deductible', models.BooleanField(default=False, help_text='Dedutível de impostos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_expenses', to='finance.category')),
            ],
            options={
                'verbose_name': 'Despesa do Negócio',
                'verbose_name_plural': 'Despesas do Negócio',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor', models.CharField(help_text='Nome do credor', max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Taxa de juros (%)', max_digits=5)),
                ('due_date', models.DateField(help_text='Data de vencimento')),
                ('description', models.TextField(blank=True, help_text='Descrição da dívida')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paid', 'Paga'), ('overdue', 'Vencida')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dívida',
                'verbose_name_plural': 'Dívidas',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do objetivo', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('target_date', models.DateField(help_text='Data alvo para alcançar o objetivo')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='Descrição da despesa')),
                ('date', models.DateField(help_text='Data da despesa')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('other', 'Outro')], default='cash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_expenses', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa Pessoal',
                'verbose_name_plural': 'Despesas Pessoais',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(help_text='Descrição da venda')),
                ('customer_name', models.CharField(blank=True, help_text='Nome do cliente', max_length=200)),
                ('date', models.DateField(help_text='Data da venda')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('check', 'Cheque'), ('other', 'Outro')], default='cash', max_length=50)),
                ('invoice_number', models.CharField(blank=True, help_text='Número da fatura', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, help_text='Descrição do orçamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='finance.category')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
    ]
