# Generated by Django 5.2.1 on 2026-01-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', '-month', '-date', '-start_date', '-created_at'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(blank=True, help_text='Data (para orçamentos diários)', null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, help_text='Data final (para orçamentos personalizados)', null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Diário'), ('monthly', 'Mensal'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(blank=True, help_text='Data inicial (para orçamentos personalizados)', null=True),
        ),
    ]
