# Generated by Django 5.2.10 on 2026-01-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_budget_options_budget_date_budget_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
    ]
