# Generated by Django 5.2.14 on 2026-05-21 00:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_budget_options_budget_date_budget_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-year', '-month', '-created_at'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='currency',
            field=models.CharField(default='AOA', max_length=3),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Única'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_currency'],
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
        migrations.CreateModel(
            name='PersonalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('source_type', models.CharField(choices=[('salary', 'Salário'), ('freelance', 'Freelance'), ('business', 'Negócio'), ('investment', 'Investimento'), ('gift', 'Presente'), ('other', 'Outro')], default='salary', max_length=20)),
                ('currency', models.CharField(default='AOA', max_length=3)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('none', 'Única'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('yearly', 'Anual')], default='none', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_incomes', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_currencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('user', 'currency_code')},
            },
        ),
    ]
