# Generated by Django 5.2.10 on 2026-05-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budget_options'),
        ('finance', '0003_alter_budget_options_personalexpense_currency_and_more'),
    ]

    operations = []
