# Generated by Django 5.2.10 on 2026-05-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_merge_20260521_0136'),
        ('finance', '0005_goal_contribution_debt_payment'),
    ]

    operations = []
