# Generated by Django 5.2.10 on 2026-08-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_merge_20260521_1758'),
        ('finance', '0007_alter_category_user'),
    ]

    operations = []
