# Generated by Django 6.0.6 on 2026-08-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='AOA', help_text='Original budget currency (never overwrite on display FX)', max_length=3),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='currency',
            field=models.CharField(default='AOA', help_text='Original expense currency', max_length=3),
        ),
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.CharField(default='AOA', help_text='Original debt currency', max_length=3),
        ),
        migrations.AddField(
            model_name='debt',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionais'),
        ),
        migrations.AddField(
            model_name='goal',
            name='currency',
            field=models.CharField(default='AOA', help_text='Original goal currency', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='AOA', help_text='Original sale currency', max_length=3),
        ),
    ]
