# Generated by Django 6.0.6 on 2026-08-11 22:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_currency_locale_fx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('spending_limit', models.DecimalField(decimal_places=2, default=0, help_text='Monthly spending budget (cap for actual expenses)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('savings_target', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='AOA', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('last_budget_alert_level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('rent', 'Rent'), ('transport', 'Transport'), ('food', 'Food'), ('electricity', 'Electricity'), ('internet', 'Internet'), ('school', 'School'), ('family', 'Family'), ('debt', 'Debt payments'), ('savings', 'Savings'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=32)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('bucket', models.CharField(choices=[('needs', 'Needs / fixed'), ('wants', 'Wants'), ('savings', 'Savings'), ('debt', 'Debt')], default='needs', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.monthlyfinancialplan')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
