# Generated by Django 6.0.6 on 2026-08-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_monthly_plan_share_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted into the debt currency at payment time', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='currency',
            field=models.CharField(default='AOA', max_length=3),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='goalcontribution',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted into the goal currency at payment time', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='goalcontribution',
            name='currency',
            field=models.CharField(default='AOA', max_length=3),
        ),
        migrations.AddField(
            model_name='goalcontribution',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
