# Generated by Django 6.0.6 on 2026-08-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_goal_debt_payment_fx_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='provider_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp reported by the market provider for this quote', null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Market data provider name (or seed)', max_length=64),
        ),
    ]
