# Generated by Django 5.2.10 on 2026-08-13 19:35
# Merge PA-only 0008_merge leaf with exchangerate source/provider_updated_at.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_merge_20260808_1635'),
        ('finance', '0011_exchangerate_source_provider_updated_at'),
    ]

    operations = []
