# Generated by Django 6.0.6 on 2026-08-17 22:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_debtpayment_fx_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_budget_alert_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted into display_currency at save time', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='display_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='exchange_rate_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='exchange_rate_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='receipt',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='receipt',
            name='merchant_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('other', 'Outro')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='suggested_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'A processar'), ('processed', 'Processado'), ('failed', 'Falhou'), ('low_confidence', 'Confiança baixa')], default='pending', max_length=20),
        ),
    ]
