# Generated by Django 6.0.1 on 2026-01-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonattachment',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do anexo'),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('other', 'Outro')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Conteúdo em texto da aula (HTML permitido)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do YouTube (não listado) ou Google Drive'),
        ),
    ]
