# Generated by Django 6.0.1 on 2026-01-24 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_finalexam_examresult_lessonquiz_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Curso associado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Aula associada (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson'),
        ),
    ]
