# Generated by Django 5.2.14 on 2026-05-21 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_course_lesson_to_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Referral code used when enrolling (for course-specific referrals)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ReferralPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned (1 point = 1000 KZ)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', help_text='Status of the points award', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the points', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referral_points', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(help_text='Enrollment that triggered the points', on_delete=django.db.models.deletion.CASCADE, related_name='referral_points', to='courses.enrollment')),
                ('referred_user', models.ForeignKey(help_text='User who enrolled from the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referral_points_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='User who shared and earned points', on_delete=django.db.models.deletion.CASCADE, related_name='referral_points_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, help_text='Social media platform (facebook, twitter, whatsapp, etc.)', max_length=50)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course that was shared', on_delete=django.db.models.deletion.CASCADE, related_name='referral_shares', to='courses.course')),
                ('referrer', models.ForeignKey(help_text='User who shared the course', on_delete=django.db.models.deletion.CASCADE, related_name='referral_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Ganho'), ('spent', 'Gasto'), ('expired', 'Expirado'), ('admin_adjustment', 'Ajuste Admin')], max_length=20)),
                ('points', models.DecimalField(decimal_places=2, help_text='Points amount (positive for earned, negative for spent)', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text="User's balance after this transaction", max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_points', models.ForeignKey(blank=True, help_text='Related referral points if this is from a referral', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.referralpoints')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referralpoints',
            index=models.Index(fields=['referrer', 'status'], name='courses_ref_referre_dffd09_idx'),
        ),
        migrations.AddIndex(
            model_name='referralpoints',
            index=models.Index(fields=['referred_user'], name='courses_ref_referre_608cbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referralpoints',
            unique_together={('referrer', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='referralshare',
            index=models.Index(fields=['referrer', 'course'], name='courses_ref_referre_a84504_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['user', 'transaction_type'], name='courses_use_user_id_5df6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['user', 'created_at'], name='courses_use_user_id_bbb249_idx'),
        ),
    ]
