# Generated by Django 6.1 on 2026-08-21 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_backfill_official_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userexamanswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userquizanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='public_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='valid', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='completion_lesson_percent',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='completion_quiz_percent',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_final_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresult',
            name='earned_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='examresult',
            name='maximum_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='finalexam',
            name='multi_scoring',
            field=models.CharField(default='all_or_nothing', max_length=20),
        ),
        migrations.AddField(
            model_name='finalexam',
            name='randomize_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finalexam',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finalexam',
            name='show_correct_after',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='finalexam',
            name='show_explanations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='allow_change_answers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='multi_scoring',
            field=models.CharField(choices=[('all_or_nothing', 'All or nothing'), ('partial', 'Partial credit')], default='all_or_nothing', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='randomize_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='show_correct_after',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessonquiz',
            name='show_explanations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='earned_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='maximum_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='choice_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='earned_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userexamanswer',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.examresult'),
        ),
        migrations.AddField(
            model_name='userquizanswer',
            name='choice_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userquizanswer',
            name='earned_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='userquizanswer',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizresult'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('unpublished', 'Unpublished')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.choice'),
        ),
        migrations.AlterField(
            model_name='userquizanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.choice'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('user', 'quiz', 'attempt_number')},
        ),
        migrations.CreateModel(
            name='QuizAttemptDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='courses.lessonquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
